apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: qbittorrent-config-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Amsterdam"
            - name: WEBUI_PORT
              value: "8080"
            - name: TORRENTING_PORT
              value: "6881"
          ports:
            - containerPort: 8080
              name: webui
            - containerPort: 6881
              name: torrenting
            - containerPort: 6881
              protocol: UDP
              name: torrenting-udp
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: media-downloads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
spec:
  type: ClusterIP
  selector:
    app: qbittorrent
  ports:
    - port: 8080
      targetPort: 8080
      name: webui
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-torrent
  namespace: media
spec:
  type: LoadBalancer
  selector:
    app: qbittorrent
  ports:
    - port: 6881
      targetPort: 6881
      protocol: TCP
      name: torrenting
    - port: 6881
      targetPort: 6881
      protocol: UDP
      name: torrenting-udp
