apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - sabnzbd/manifests.yaml
  - sonarr/manifests.yaml
  - radarr/manifests.yaml
  - plex/manifests.yaml
