apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/services/plex/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/services/radarr/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/services/sonarr/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-config-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/services/sabnzbd/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/services/qbittorrent/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-downloads-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  hostPath:
    path: /data/media/downloads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-sources-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  hostPath:
    path: /data/media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-incomplete-downloads-pv
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/services/sabnzbd/incomplete-downloads
