apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-downloads-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/media/downloads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-sources-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/media
---
# Shared Persistent Volume Claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: media-downloads-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-sources-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: media-sources-pv
