apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  volumeName: media-downloads-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-sources-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: media-sources-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-incomplete-downloads-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 150Gi
  volumeName: sabnzbd-incomplete-downloads-pv
