apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/services/plex/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/services/radarr/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/services/sonarr/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-config-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/services/sabnzbd/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-downloads-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  hostPath:
    path: /data/media/downloads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-sources-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  hostPath:
    path: /data/media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-incomplete-downloads-pv
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/services/sabnzbd/incomplete-downloads
---
# Shared Persistent Volume Claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  volumeName: media-downloads-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-sources-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: media-sources-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-incomplete-downloads-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 150Gi
  volumeName: sabnzbd-incomplete-downloads-pv
