apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  volumeName: plex-config-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: lscr.io/linuxserver/plex:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Amsterdam
          ports:
            - containerPort: 32400
          volumeMounts:
            - name: config
              mountPath: /config
            - name: movies
              mountPath: /movies
              subPath: movies
            - name: tv
              mountPath: /tv
              subPath: tv
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-config-pvc
        - name: movies
          persistentVolumeClaim:
            claimName: media-sources-pvc
        - name: tv
          persistentVolumeClaim:
            claimName: media-sources-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  type: LoadBalancer
  selector:
    app: plex
  ports:
    - port: 32400
      targetPort: 32400