apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: sabnzbd-config-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
        - name: sabnzbd
          image: lscr.io/linuxserver/sabnzbd:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Amsterdam"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: incomplete-downloads
              mountPath: /incomplete-downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sabnzbd-config-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: media-downloads-pvc
        - name: incomplete-downloads
          persistentVolumeClaim:
            claimName: sabnzbd-incomplete-downloads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: media
spec:
  type: LoadBalancer
  selector:
    app: sabnzbd
  ports:
    - port: 8080
      targetPort: 8080
